config/routes.rb
Rails.application.routes.draw do
  # verb "/path", to: "controller#action"

  get "/pets", to: "pets#index"

  get "/pets/new", to: "pets#new", as: "new_pet"
  post "/pets", to: "pets#create"

  get "/pets/:id/edit", to: "pets#edit", as: "edit_pet"
  patch "/pets/:id", to: "pets#update"

  get "/pets/:id", to: "pets#show", as: "pet"

  delete "/pets/:id", to: "pets#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = ["Dog", "Cat", "Turtle", "Bird"]

  validates :name, presence: true
  validates :species, inclusion: { in: SPECIES }

  def found_days_ago
    Date.today.mjd - found_on.mjd
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.save
    redirect_to pet_path(@pet)
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update(pet_params)
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy

    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPetsLivecode</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pets/_form.html.erb
<%= simple_form_for @pet do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :species, collection: Pet::SPECIES %>
  <%= f.input :found_on %>
  <%= f.submit %>
<% end %>

app/views/pets/edit.html.erb
<h1>Edit this pet</h1>

<%= render "form" %>

<%= link_to "Back to my pet", pet_path %>

app/views/pets/index.html.erb
<h1>All my Pets</h1>

<ul>
  <% @pets.each do |pet| %>
    <li><%= link_to pet.name, pet_path(pet) %>, found <%= pet.found_days_ago %> days ago</li>
  <% end %>
</ul>

<%= link_to "Found a pet!", new_pet_path %>

app/views/pets/new.html.erb
<h1>New pet</h1>

<%= render "form" %>

<%= link_to "Back to pets", pets_path %>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>
<h2><%= @pet.address %></h2>
<p><%= @pet.species %> | Found <%= @pet.found_days_ago %> days ago</p>

<%= link_to "Back to pets", pets_path %>
<%= link_to "Edit this pet", edit_pet_path(@pet) %>
<%= link_to "Delete this pet", pet_path(@pet), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>